export interface User {
    id: string;
    name: string;
    username: string;
    email: string;
    avatarInitial: string;
    bio: string;
    website: string;
    stripeConnected: boolean;
    totalEarned: number;
    thisMonth: number;
    availableToWithdraw: number;
    joinedDate: string;
    hasSeenOnboarding: boolean;
}

export const currentUser: User = {
    id: "u_123",
    name: "Alex Creator",
    username: "alexcreator",
    email: "alex@example.com",
    avatarInitial: "A",
    bio: "Creating tools and resources for designers and developers.",
    website: "https://alexcreator.com",
    stripeConnected: false,
    totalEarned: 47.32,
    thisMonth: 12.80,
    availableToWithdraw: 22.10,
    joinedDate: "2024-01-15T00:00:00Z",
    hasSeenOnboarding: false,
};

export const mockLinks = [
    {
        id: "link_01",
        slug: "design-system-pro",
        title: "Pro Design System UI Kit",
        description: "A complete professional design system for Figma with 1000+ components.",
        fileType: "ZIP",
        fileName: "DesignSystemPro.zip",
        fileSize: "24.5 MB",
        adCount: 3,
        donateEnabled: true,
        isActive: true,
        viewCount: 1420,
        unlockCount: 840,
        earned: 15.20,
        conversionRate: "59.1%",
        createdAt: "2024-02-10T10:00:00Z",
        geography: [{ country: "US", percent: 45 }, { country: "UK", percent: 20 }, { country: "IN", percent: 15 }],
        deviceSplit: { mobile: 65, desktop: 30, tablet: 5 },
    },
    {
        id: "link_02",
        slug: "midjourney-prompts",
        title: "100+ Midjourney Prompts for Character Design",
        description: "My personal collection of prompts for generating consistent and detailed characters.",
        fileType: "PDF",
        fileName: "Midjourney_Characters.pdf",
        fileSize: "4.2 MB",
        adCount: 2,
        donateEnabled: false,
        isActive: true,
        viewCount: 890,
        unlockCount: 612,
        earned: 8.56,
        conversionRate: "68.7%",
        createdAt: "2024-03-01T14:30:00Z",
        geography: [{ country: "US", percent: 50 }, { country: "CA", percent: 15 }, { country: "AU", percent: 10 }],
        deviceSplit: { mobile: 80, desktop: 15, tablet: 5 },
    },
    {
        id: "link_03",
        slug: "notion-habit-tracker",
        title: "Ultimate Notion Habit Tracker",
        description: "Track your daily, weekly, and monthly habits with this aesthetic Notion template.",
        fileType: "LINK",
        fileName: "Notion Template Link",
        fileSize: "0 KB",
        adCount: 1,
        donateEnabled: true,
        isActive: true,
        viewCount: 3045,
        unlockCount: 2150,
        earned: 22.45,
        conversionRate: "70.6%",
        createdAt: "2024-01-20T09:15:00Z",
        geography: [{ country: "US", percent: 40 }, { country: "IN", percent: 25 }, { country: "UK", percent: 15 }],
        deviceSplit: { mobile: 55, desktop: 40, tablet: 5 },
    },
    {
        id: "link_04",
        slug: "react-auth-boilerplate",
        title: "React Auth Boilerplate (Firebase)",
        description: "Start your next project quickly with this pre-configured React + Firebase authentication boilerplate.",
        fileType: "ZIP",
        fileName: "react-auth-starter.zip",
        fileSize: "1.8 MB",
        adCount: 2,
        donateEnabled: false,
        isActive: true,
        viewCount: 450,
        unlockCount: 120,
        earned: 1.11,
        conversionRate: "26.6%",
        createdAt: "2024-04-05T16:45:00Z",
        geography: [{ country: "IN", percent: 40 }, { country: "US", percent: 30 }, { country: "DE", percent: 10 }],
        deviceSplit: { mobile: 20, desktop: 78, tablet: 2 },
    },
    {
        id: "link_05",
        slug: "freelance-contract-template",
        title: "Freelance Client Contract Template",
        description: "The exact contract I use to protect myself as a freelance designer.",
        fileType: "DOC",
        fileName: "Freelance_Contract.docx",
        fileSize: "125 KB",
        adCount: 3,
        donateEnabled: true,
        isActive: false,
        viewCount: 210,
        unlockCount: 85,
        earned: 0.00,
        conversionRate: "40.4%",
        createdAt: "2023-11-12T11:20:00Z",
        geography: [{ country: "US", percent: 70 }, { country: "UK", percent: 10 }, { country: "CA", percent: 5 }],
        deviceSplit: { mobile: 50, desktop: 45, tablet: 5 },
    },
    {
        id: "link_06",
        slug: "youtube-thumbnail-pack",
        title: "Viral YouTube Thumbnail PSDs",
        description: "5 fully editable Photoshop templates for high-CTR thumbnails.",
        fileType: "ZIP",
        fileName: "YT_Thumbnails.zip",
        fileSize: "45.2 MB",
        adCount: 2,
        donateEnabled: false,
        isActive: true,
        viewCount: 110,
        unlockCount: 0,
        earned: 0.00,
        conversionRate: "0%",
        createdAt: "2024-04-18T08:00:00Z",
        geography: [],
        deviceSplit: { mobile: 0, desktop: 0, tablet: 0 },
    }
];

export const mockActivity = [
    { id: "act_1", type: "unlock", description: "Someone in United States unlocked", timestamp: "2 mins ago", earned: 0.04, resourceTitle: "Pro Design System UI Kit" },
    { id: "act_2", type: "unlock", description: "Someone in India unlocked", timestamp: "15 mins ago", earned: 0.02, resourceTitle: "React Auth Boilerplate" },
    { id: "act_3", type: "tip", description: "Tree donation made from unlock", timestamp: "1 hour ago", earned: 0.00, resourceTitle: "Notion Habit Tracker" },
    { id: "act_4", type: "unlock", description: "Someone in UK unlocked", timestamp: "2 hours ago", earned: 0.03, resourceTitle: "Ultimate Notion Habit Tracker" },
    { id: "act_5", type: "unlock", description: "Someone in Canada unlocked", timestamp: "5 hours ago", earned: 0.04, resourceTitle: "100+ Midjourney Prompts" },
    { id: "act_6", type: "payout", description: "Payout to Stripe initiated", timestamp: "Yesterday", earned: -25.00, resourceTitle: "" },
    { id: "act_7", type: "unlock", description: "Someone in Australia unlocked", timestamp: "Yesterday", earned: 0.04, resourceTitle: "100+ Midjourney Prompts" },
    { id: "act_8", type: "creation", description: "Created new link", timestamp: "3 days ago", earned: 0.00, resourceTitle: "Viral YouTube Thumbnail PSDs" },
    { id: "act_9", type: "unlock", description: "Someone in Germany unlocked", timestamp: "3 days ago", earned: 0.03, resourceTitle: "Pro Design System UI Kit" },
    { id: "act_10", type: "unlock", description: "Someone in France unlocked", timestamp: "4 days ago", earned: 0.03, resourceTitle: "Pro Design System UI Kit" },
];

export const mockPayoutHistory = [
    { id: "pay_1", amount: 25.00, status: "pending", period: "April 2024", transferId: "tr_pending", createdAt: "2024-04-18T10:00:00Z" },
    { id: "pay_2", amount: 32.50, status: "completed", period: "March 2024", transferId: "tr_18fHajXw9", createdAt: "2024-04-01T10:00:00Z" },
    { id: "pay_3", amount: 15.20, status: "completed", period: "February 2024", transferId: "tr_92kLpsVn2", createdAt: "2024-03-01T10:00:00Z" },
    { id: "pay_4", amount: 20.00, status: "completed", period: "January 2024", transferId: "tr_34mBrtYq1", createdAt: "2024-02-01T10:00:00Z" },
];

export const mockEarningsData = [
    { date: "Apr 5", amount: 0.45 },
    { date: "Apr 6", amount: 0.60 },
    { date: "Apr 7", amount: 1.10 },
    { date: "Apr 8", amount: 0.85 },
    { date: "Apr 9", amount: 1.40 },
    { date: "Apr 10", amount: 2.10 },
    { date: "Apr 11", amount: 1.80 },
    { date: "Apr 12", amount: 1.50 },
    { date: "Apr 13", amount: 0.90 },
    { date: "Apr 14", amount: 1.25 },
    { date: "Apr 15", amount: 1.70 },
    { date: "Apr 16", amount: 2.45 },
    { date: "Apr 17", amount: 2.15 },
    { date: "Apr 18", amount: 1.65 },
];

export const mockCreatorProfile = { ...currentUser, links: mockLinks.filter(l => l.isActive) };

export const mockExploreResources: any[] = [
    {
        id: "exp_1",
        slug: "design-system-pro",
        title: "Pro Design System UI Kit",
        creatorName: "Alex Creator",
        creatorHandle: "alexcreator",
        creatorAvatar: "A",
        verified: true,
        fileType: "ZIP",
        adCount: 3,
        unlockCount: "1.2K",
        category: "Templates",
    },
    {
        id: "exp_2",
        slug: "ai-prompt-pack",
        title: "500+ ChatGPT Prompts for Marketing",
        creatorName: "Sarah M.",
        creatorHandle: "sarahmarket",
        creatorAvatar: "S",
        verified: false,
        fileType: "PDF",
        adCount: 2,
        unlockCount: "840",
        category: "Prompts",
    },
    {
        id: "exp_3",
        slug: "freelance-notion",
        title: "Freelance OS Notion Template",
        creatorName: "Dev Dave",
        creatorHandle: "devdave",
        creatorAvatar: "D",
        verified: true,
        fileType: "LINK",
        adCount: 2,
        unlockCount: "2.1K",
        category: "Templates",
    },
    {
        id: "exp_4",
        slug: "luts-pack",
        title: "Cinematic Video LUTs Pack",
        creatorName: "Video Creator",
        creatorHandle: "vidcreator",
        creatorAvatar: "V",
        verified: false,
        fileType: "ZIP",
        adCount: 3,
        unlockCount: "350",
        category: "Videos",
    },
    {
        id: "exp_5",
        slug: "resume-template",
        title: "Modern Minimalist Resume Template",
        creatorName: "Career Coach",
        creatorHandle: "careercoach",
        creatorAvatar: "C",
        verified: false,
        fileType: "DOC",
        adCount: 1,
        unlockCount: "5.4K",
        category: "Guides",
    },
    {
        id: "exp_6",
        slug: "procreate-brushes",
        title: "Watercolor Procreate Brushes",
        creatorName: "Artist Anna",
        creatorHandle: "annaart",
        creatorAvatar: "A",
        verified: true,
        fileType: "ZIP",
        adCount: 2,
        unlockCount: "920",
        category: "Tools",
    },
    {
        id: "exp_7",
        slug: "startup-pitch",
        title: "Startup Pitch Deck Template",
        creatorName: "Founder Joe",
        creatorHandle: "founderjoe",
        creatorAvatar: "F",
        verified: false,
        fileType: "PDF",
        adCount: 3,
        unlockCount: "135",
        category: "Templates",
    },
    {
        id: "exp_8",
        slug: "code-snippets",
        title: "100 Useful JS Code Snippets",
        creatorName: "JS Ninja",
        creatorHandle: "jsninja",
        creatorAvatar: "J",
        verified: true,
        fileType: "PDF",
        adCount: 2,
        unlockCount: "3.2K",
        category: "Guides",
    },
    {
        id: "exp_9",
        slug: "photo-presets",
        title: "Moody Moodroom Presets",
        creatorName: "Photo Pro",
        creatorHandle: "photopro",
        creatorAvatar: "P",
        verified: false,
        fileType: "ZIP",
        adCount: 2,
        unlockCount: "420",
        category: "Images",
    },
    {
        id: "exp_10",
        slug: "budget-tracker",
        title: "Monthly Budget Excel Sheet",
        creatorName: "Finance Guy",
        creatorHandle: "financeguy",
        creatorAvatar: "F",
        verified: true,
        fileType: "DOC",
        adCount: 1,
        unlockCount: "8.1K",
        category: "Templates",
    },
    {
        id: "exp_11",
        slug: "seo-checklist",
        title: "Ultimate 2024 SEO Checklist",
        creatorName: "SEO Master",
        creatorHandle: "seomas",
        creatorAvatar: "S",
        verified: false,
        fileType: "PDF",
        adCount: 2,
        unlockCount: "1.1K",
        category: "Guides",
    },
    {
        id: "exp_12",
        slug: "fonts-pack",
        title: "3 Premium Serif Fonts",
        creatorName: "Type Co",
        creatorHandle: "typeco",
        creatorAvatar: "T",
        verified: true,
        fileType: "ZIP",
        adCount: 3,
        unlockCount: "670",
        category: "Other",
    },
];
